// Code generated by coz. DO NOT EDIT.
/**
 * Info of the-component
 * @module the-info
 * @version 2.0.3
 */
'use strict'

import TheInfo from './TheInfo'
import TheInfoStyle from './TheInfoStyle'

export default TheInfo

export {
  TheInfo,
  TheInfoStyle
}
